language: java
jdk: 
  - openjdk7
before_deploy:
  - ./gradlew check
  - ./gradlew seleniumXvfb
deploy:
  provider: heroku
  api_key:nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC4GIgqXdPOkehPwITfExrH+NrT\nq3uJlNS0ZWeEd/QCVLayVGTScAzYrJZcC3hw09rHe9fQv0VRtvfGN1O4Zh4Q1cTI\n1DBswD5F68SFxWN/DbPafCmu+wuCEr767iCqw8JwxynChyRYMOcdf22VQz8QUbfb\nCKwHayMOtCC8XiPLBQIDAQAB
    secure:
  app:
    master: hilmario10
  on:
    repo: hilmario10/Sidannaverkefni