language: java
jdk: 
  - openjdk7
before_deploy:
  - ./gradlew check
  - ./gradlew seleniumXvfb
deploy:
  provider: heroku
  api_key:
    secure:
  app:
    master: hilmario10
  on:
    repo: hilmario10/Sidannaverkefni