deploy:
  provider: heroku
  api_key:
    secure: vuSGBb+eEejhJVm9UZQPxP8wlZTp3wATeXgUcDl6PyGxhERcwhzUn3Pe2lsQr/ljoAl0p6Q45vqgw84KP7C2G8MzmbFR8U65/QgwseQqxiuI7ecYtaIIpr7wj6gApJvP93091SgZlz4yt5RMs0Pt/ydOeeQS3oXuC8LgOWMTU2c=
  app: Sidannaverkefni
  on:
    repo: hilmario10/Sidannaverkefni
