language: java
jdk:
- openjdk7
before_deploy:
- ./gradlew check
- ./gradlew seleniumXvfb
deploy:
  provider: heroku
  api_key:
    secure: f5Oks1DvSvJMsMwIC3+5pwYMD786peNFEy9Fsqunc1/BUMj760ScXpNvuyaqyQeJ+xHSqI3cAbxGPAkxjI+JKBiufx7l9ml0oHnFXRrs8faO3DAv+bWsMHSx/Wryvx0PVWTknL+IqJMjgEyzhYi9MdyMwZGSg7CGPLvs+MjaRZA=
  app:
    master: hilmario10
  on:
    repo: hilmario10/Sidannaverkefni
