language: java
jdk: 
  - openjdk7
before_deploy:
  - ./gradlew check
  - ./gradlew seleniumXvfb
deploy:
  provider: heroku
  api_key:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQC/gCEhVyO5BG+LVtEJR9mza2AYFNQMyizw+o6chez4L5Wervrtlmovt2OkZfq9vmhEGMNLRDx0+jUwQloyBeALij8emsfVZyH1E2lw+6Be8nJpTUMPzLHsMJg805fol7ki2kmabCVax5CGynOba9Nfcr4iJANKIDQPhsWpw4/wdw==
  app:
    master: hilmario10
  on:
    repo: hilmario10/Sidannaverkefni